#!/bin/bash

YEAR=$(date +"%Y")
DAY=$(date +"%-d")
LANGS=("cpp" "go" "rs")

while getopts "y:d:l:i:" opt; do
	case $opt in
	y) YEAR=$OPTARG ;;
	d) DAY=$OPTARG ;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		exit 1
		;;
	esac
done

create_files() {
	for LANG in "${LANGS[@]}"; do
		FILE="${YEAR}/d${DAY}.${LANG}"
		if [ ! -f "$FILE" ]; then
			echo "Creating file $FILE..."
			touch "$FILE"
		else
			echo "File $FILE already exists."
		fi
	done

	EXAMPLE="${YEAR}/examples/d${DAY}e1"
	if [ ! -f "$EXAMPLE" ]; then
		echo "Creating example file $EXAMPLE..."
		touch "$EXAMPLE"
	else
		echo "Example file $EXAMPLE already exists."
	fi
	EXAMPLE="${YEAR}/examples/d${DAY}e2"
	if [ ! -f "$EXAMPLE" ]; then
		echo "Creating example file $EXAMPLE..."
		touch "$EXAMPLE"
	else
		echo "Example file $EXAMPLE already exists."
	fi

	INPUT="${YEAR}/inputs/d${DAY}i1"
	if [ ! -f "$INPUT" ]; then
		echo "Creating input file $INPUT..."
		touch "$INPUT"
	else
		echo "Input file $INPUT already exists."
	fi

	INPUT="${YEAR}/inputs/d${DAY}i2"
	if [ ! -f "$INPUT" ]; then
		echo "Creating input file $INPUT..."
		touch "$INPUT"
	else
		echo "Input file $INPUT already exists."
	fi
}

create_files
