#!/bin/bash

YEAR=$(date +"%Y")
DAY=$(printf "%02d" "$(date +"%-d")")
LANGS=("cpp" "go" "rs")

while getopts "y:d" opt; do
  case $opt in
  y) YEAR=$OPTARG ;;
  d) DAY=$(printf "%02d" "$OPTARG") ;;
  \?)
    echo "Invalid option: -$OPTARG" >&2
    exit 1
    ;;
  esac
done

create_files() {
  mkdir -p "$YEAR/day${DAY}"
  mkdir -p "$YEAR/examples"
  mkdir -p "$YEAR/inputs"

  for LANG in "${LANGS[@]}"; do
    FILE="${YEAR}/day${DAY}/main.${LANG}"
    if [ ! -f "$FILE" ]; then
      echo "Creating file $FILE..."
      touch "$FILE"
    else
      echo "File $FILE already exists."
    fi
  done

  EXAMPLE="${YEAR}/examples/d${DAY}e1"
  if [ ! -f "$EXAMPLE" ]; then
    echo "Creating example file $EXAMPLE..."
    touch "$EXAMPLE"
  else
    echo "Example file $EXAMPLE already exists."
  fi
  EXAMPLE="${YEAR}/examples/d${DAY}e2"
  if [ ! -f "$EXAMPLE" ]; then
    echo "Creating example file $EXAMPLE..."
    touch "$EXAMPLE"
  else
    echo "Example file $EXAMPLE already exists."
  fi

  INPUT="${YEAR}/inputs/d${DAY}i1"
  if [ ! -f "$INPUT" ]; then
    echo "Creating input file $INPUT..."
    touch "$INPUT"
  else
    echo "Input file $INPUT already exists."
  fi

  INPUT="${YEAR}/inputs/d${DAY}i2"
  if [ ! -f "$INPUT" ]; then
    echo "Creating input file $INPUT..."
    touch "$INPUT"
  else
    echo "Input file $INPUT already exists."
  fi
}

create_files
